from __future__ import annotations

from dataclasses import dataclass
from typing import Protocol, runtime_checkable

from workforce_runtime.core.agent_profile import AgentProfile
from workforce_runtime.core.agent_inbox import AgentInboxItem, AgentInboxItemStatus
from workforce_runtime.core.agent_personal_profile import AgentPersonalProfile
from workforce_runtime.core.artifact import Artifact
from workforce_runtime.core.events import Event
from workforce_runtime.core.organization import Company
from workforce_runtime.core.report import ReportContract
from workforce_runtime.core.task import TaskContract
from workforce_runtime.core.task_document import TaskDocument
from workforce_runtime.core.task_trace import TaskTraceExport
from workforce_runtime.core.work_queue import WorkItem, WorkItemStatus


@dataclass(frozen=True)
class SequencedEvent:
    sequence: int
    event: Event


@runtime_checkable
class RuntimeStore(Protocol):
    """Persistence boundary used by the runtime.

    Adapters should preserve the semantic ordering documented by each list
    method. The current SQLite adapter is the reference implementation.
    """

    def close(self) -> None: ...

    def save_company(self, company: Company) -> None: ...

    def get_company(self) -> Company | None: ...

    def save_agent(self, agent: AgentProfile) -> None: ...

    def get_agent(self, agent_id: str) -> AgentProfile | None: ...

    def list_agents(self) -> list[AgentProfile]: ...

    def save_agent_inbox_item(self, item: AgentInboxItem) -> None: ...

    def get_agent_inbox_item(self, inbox_item_id: str) -> AgentInboxItem | None: ...

    def list_agent_inbox_items(
        self,
        *,
        agent_id: str | None = None,
        status: AgentInboxItemStatus | None = None,
    ) -> list[AgentInboxItem]: ...

    def save_agent_personal_profile(self, profile: AgentPersonalProfile) -> None: ...

    def get_agent_personal_profile(self, agent_id: str) -> AgentPersonalProfile | None: ...

    def list_agent_personal_profiles(self) -> list[AgentPersonalProfile]: ...

    def save_task(self, task: TaskContract) -> None: ...

    def get_task(self, task_id: str) -> TaskContract | None: ...

    def list_tasks(self) -> list[TaskContract]: ...

    def save_report(self, report: ReportContract) -> None: ...

    def get_report(self, report_id: str) -> ReportContract | None: ...

    def list_reports_by_task(self, task_id: str) -> list[ReportContract]: ...

    def list_reports(self) -> list[ReportContract]: ...

    def save_event(self, event: Event) -> None: ...

    def list_events(self) -> list[Event]: ...

    def list_events_after(self, sequence: int = 0, *, limit: int = 500) -> list[SequencedEvent]: ...

    def latest_event_sequence(self) -> int: ...

    def save_artifact(self, artifact: Artifact) -> None: ...

    def list_artifacts_by_task(self, task_id: str) -> list[Artifact]: ...

    def list_artifacts(self) -> list[Artifact]: ...

    def save_task_document(self, document: TaskDocument) -> None: ...

    def get_task_document(self, doc_id: str) -> TaskDocument | None: ...

    def list_task_documents_by_task(self, task_id: str) -> list[TaskDocument]: ...

    def list_task_documents(self) -> list[TaskDocument]: ...

    def save_task_trace_export(self, trace: TaskTraceExport) -> None: ...

    def get_task_trace_export(self, trace_id: str) -> TaskTraceExport | None: ...

    def list_task_trace_exports_by_task(self, task_id: str) -> list[TaskTraceExport]: ...

    def list_task_trace_exports(self) -> list[TaskTraceExport]: ...

    def save_work_item(self, item: WorkItem) -> None: ...

    def get_work_item(self, work_item_id: str) -> WorkItem | None: ...

    def get_work_item_by_idempotency_key(self, idempotency_key: str) -> WorkItem | None: ...

    def list_work_items(self, *, status: WorkItemStatus | None = None) -> list[WorkItem]: ...
