from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path


def mcp_request(process: subprocess.Popen[str], message: dict[str, object]) -> dict[str, object]:
    assert process.stdin is not None
    assert process.stdout is not None
    process.stdin.write(json.dumps(message) + "\n")
    process.stdin.flush()
    return json.loads(process.stdout.readline())


def call_tool(
    process: subprocess.Popen[str],
    request_id: int,
    name: str,
    arguments: dict[str, object],
) -> dict[str, object]:
    response = mcp_request(
        process,
        {
            "jsonrpc": "2.0",
            "id": request_id,
            "method": "tools/call",
            "params": {"name": name, "arguments": arguments},
        },
    )
    if "error" in response:
        raise RuntimeError(response["error"])
    return response


def main() -> None:
    task_path = Path(os.environ["WORKFORCE_TASK_CONTRACT_PATH"])
    db_path = os.environ["WORKFORCE_RUNTIME_DB"]
    workspace = Path(os.environ["WORKFORCE_WORKSPACE"])
    agent_id = os.environ["WORKFORCE_AGENT_ID"]
    manager_id = os.environ.get("WORKFORCE_MANAGER_ID") or "engineering_manager"

    task = json.loads(task_path.read_text())

    parser_path = workspace / "parser.py"
    parser_path.write_text(
        """def parse_bool(value: str) -> bool:
    normalized = value.strip().lower()
    if normalized in {"true", "yes", "1"}:
        return True
    if normalized in {"false", "no", "0"}:
        return False
    raise ValueError(f"cannot parse boolean: {value}")
"""
    )

    pytest_result = subprocess.run(
        [sys.executable, "-m", "pytest", "-q"],
        cwd=workspace,
        capture_output=True,
        text=True,
        check=False,
    )
    test_log_path = workspace / "artifacts" / task["task_id"] / "pytest.log"
    test_log_path.parent.mkdir(parents=True, exist_ok=True)
    test_log_path.write_text(pytest_result.stdout + pytest_result.stderr)

    diff_result = subprocess.run(
        ["git", "diff", "--"],
        cwd=workspace,
        capture_output=True,
        text=True,
        check=False,
    )
    diff_path = workspace / "artifacts" / task["task_id"] / "diff.patch"
    diff_path.write_text(diff_result.stdout)

    process = subprocess.Popen(
        [sys.executable, "-m", "workforce_runtime", "--db", db_path, "mcp", "serve"],
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        bufsize=1,
    )
    try:
        mcp_request(process, {"jsonrpc": "2.0", "id": 1, "method": "initialize", "params": {}})
        call_tool(
            process,
            2,
            "submit_artifact",
            {
                "agent_id": agent_id,
                "task_id": task["task_id"],
                "artifact_type": "test_log",
                "path": str(test_log_path),
                "description": "pytest output from parser fix demo.",
            },
        )
        call_tool(
            process,
            3,
            "submit_artifact",
            {
                "agent_id": agent_id,
                "task_id": task["task_id"],
                "artifact_type": "git_diff",
                "path": str(diff_path),
                "description": "Patch generated by mock parser worker.",
            },
        )
        status = "completed" if pytest_result.returncode == 0 else "failed"
        response = call_tool(
            process,
            4,
            "report",
            {
                "from_agent_id": agent_id,
                "to_agent_id": manager_id,
                "task_id": task["task_id"],
                "summary": "Fixed boolean parser handling and ran pytest.",
                "status": status,
                "work_done": [
                    "Updated parser.py boolean parsing",
                    "Ran pytest for the sample repository",
                    "Submitted diff and test log artifacts",
                ],
                "evidence": [
                    {"type": "test_log", "path": str(test_log_path)},
                    {"type": "git_diff", "path": str(diff_path)},
                ],
                "risks": [],
                "blockers": [] if status == "completed" else ["pytest failed"],
                "confidence": 0.92 if status == "completed" else 0.2,
                "cost": {"tokens_used": 0, "runtime_seconds": 0, "tool_calls": 3},
                "next_action": "Ready for manager review.",
                "requires_decision": False,
                "alignment_check": "Tests pass and required artifacts were submitted.",
            },
        )
    finally:
        assert process.stdin is not None
        process.stdin.close()
        process.wait(timeout=5)

    print(json.dumps(response["result"]["structuredContent"]))
    raise SystemExit(pytest_result.returncode)


if __name__ == "__main__":
    main()
