from __future__ import annotations

import sqlite3
from uuid import uuid4

import pytest

from workforce_runtime.core import (
    AgentInboxItem,
    AgentProfile,
    Artifact,
    Budget,
    Event,
    ReportContract,
    TaskContract,
    TaskTraceExport,
    UsageCost,
    WorkItem,
)
from workforce_runtime.server.runtime import WorkforceRuntime
from workforce_runtime.storage import FileStore, MySQLStore, RuntimeStore, SQLiteStore, create_runtime_store


def make_agent() -> AgentProfile:
    return AgentProfile(
        id="codex_worker",
        name="Codex Worker",
        role="Software Engineer",
        department="Engineering",
        manager_id=None,
        worker_type="codex",
        permissions=["read_repo", "run_tests", "submit_artifact", "report"],
        budget=Budget(max_tokens=1000, max_runtime_seconds=300, max_tool_calls=20),
    )


def make_task(status: str = "created") -> TaskContract:
    return TaskContract(
        task_id="task_001",
        title="Fix failing test",
        objective="Fix the failing parser test.",
        assigned_to="codex_worker",
        assigned_by="engineering_manager",
        acceptance_criteria=["Tests pass"],
        budget=Budget(max_tokens=1000, max_runtime_seconds=300, max_tool_calls=20),
        status=status,
    )


def make_report() -> ReportContract:
    return ReportContract(
        report_id="report_001",
        from_agent_id="codex_worker",
        to_agent_id="engineering_manager",
        task_id="task_001",
        summary="Fixed the failing test.",
        status="completed",
        work_done=["Updated parser", "Ran pytest"],
        evidence=[{"type": "test_log", "path": "artifacts/task_001/test.log"}],
        risks=[],
        blockers=[],
        confidence=0.88,
        cost=UsageCost(tokens_used=500, runtime_seconds=60, tool_calls=4),
        next_action="Ready for review.",
        requires_decision=False,
        alignment_check="Meets acceptance criteria.",
    )


def test_sqlite_store_saves_and_loads_agent_task_report_event_and_artifact(tmp_path) -> None:
    db_path = tmp_path / "runtime.sqlite"
    with SQLiteStore(db_path) as store:
        agent = make_agent()
        store.save_agent(agent)
        assert store.get_agent("codex_worker") == agent

        task = make_task()
        store.save_task(task)
        loaded_task = store.get_task("task_001")
        assert loaded_task == task

        loaded_task.status = "completed"
        loaded_task.budget.record_usage(tokens=500, runtime_seconds=60, tool_calls=4)
        store.save_task(loaded_task)

        updated_task = store.get_task("task_001")
        assert updated_task.status == "completed"
        assert updated_task.budget.tokens_used == 500
        assert store.list_tasks() == [updated_task]

        report = make_report()
        store.save_report(report)
        assert store.list_reports_by_task("task_001") == [report]

        event = Event(
            event_id="event_001",
            event_type="task_completed",
            actor_id="codex_worker",
            task_id="task_001",
            payload={"status": "completed"},
        )
        store.save_event(event)
        assert store.list_events() == [event]

        artifact = Artifact(
            artifact_id="artifact_001",
            task_id="task_001",
            agent_id="codex_worker",
            type="git_diff",
            path="artifacts/task_001/diff.patch",
            description="Patch generated by worker.",
        )
        store.save_artifact(artifact)
        assert store.list_artifacts_by_task("task_001") == [artifact]

        trace = TaskTraceExport(
            trace_id="tasktrace_task_001",
            task_id="task_001",
            path="task_traces/task_001.trace.json",
            payload={"task_id": "task_001", "events": [event.model_dump(mode="json")]},
        )
        store.save_task_trace_export(trace)
        assert store.get_task_trace_export("tasktrace_task_001") == trace
        assert store.list_task_trace_exports_by_task("task_001") == [trace]

        work_item = WorkItem(
            work_item_id="work_001",
            kind="llm_request",
            agent_id="codex_worker",
            task_id="task_001",
            payload={"prompt": "fix"},
            model="openai/gpt-oss-120b:free",
        )
        store.save_work_item(work_item)
        assert store.get_work_item("work_001") == work_item
        assert store.get_work_item_by_idempotency_key("missing") is None
        assert store.list_work_items(status="queued") == [work_item]

        inbox_item = AgentInboxItem(
            inbox_item_id="inbox_001",
            agent_id="codex_worker",
            kind="assignment",
            task_id="task_001",
            from_agent_id="engineering_manager",
            payload={"task_id": "task_001"},
        )
        store.save_agent_inbox_item(inbox_item)
        assert store.get_agent_inbox_item("inbox_001") == inbox_item
        assert store.list_agent_inbox_items(agent_id="codex_worker", status="queued") == [inbox_item]


def test_sqlite_store_satisfies_runtime_store_protocol(tmp_path) -> None:
    with SQLiteStore(tmp_path / "runtime.sqlite") as store:
        assert isinstance(store, RuntimeStore)


def test_runtime_store_factory_supports_sqlite_and_mysql(tmp_path) -> None:
    store = create_runtime_store("sqlite", tmp_path / "runtime.sqlite")
    try:
        assert isinstance(store, SQLiteStore)
    finally:
        store.close()

    if not _mysql_available():
        pytest.skip("MySQL is not available")
    mysql_store = create_runtime_store("mysql", f"workforce_test_{tmp_path.name}")
    try:
        assert isinstance(mysql_store, MySQLStore)
    finally:
        mysql_store.close()


def test_workforce_runtime_accepts_injected_store_without_owning_it(tmp_path) -> None:
    store = SQLiteStore(tmp_path / "runtime.sqlite")
    try:
        runtime = WorkforceRuntime(tmp_path / "ignored.sqlite", store=store)
        runtime.close()

        agent = make_agent()
        store.save_agent(agent)
        assert store.get_agent(agent.id) == agent
    finally:
        store.close()


def test_sqlite_events_are_append_only(tmp_path) -> None:
    with SQLiteStore(tmp_path / "runtime.sqlite") as store:
        first = Event(event_id="event_001", event_type="created", actor_id="ceo")
        second = Event(event_id="event_002", event_type="assigned", actor_id="ceo")

        store.save_event(first)
        store.save_event(second)

        assert [event.event_id for event in store.list_events()] == ["event_001", "event_002"]
        with pytest.raises(sqlite3.IntegrityError):
            store.save_event(first)


def test_sqlite_store_lists_events_after_sequence(tmp_path) -> None:
    with SQLiteStore(tmp_path / "runtime.sqlite") as store:
        first = Event(event_id="event_001", event_type="created", actor_id="ceo")
        second = Event(event_id="event_002", event_type="assigned", actor_id="ceo")

        store.save_event(first)
        store.save_event(second)

        assert store.latest_event_sequence() == 2
        assert [item.sequence for item in store.list_events_after(0)] == [1, 2]
        assert [item.event.event_id for item in store.list_events_after(1)] == ["event_002"]
        assert store.list_events_after(2) == []


def test_mysql_store_round_trips_core_records(tmp_path) -> None:
    if not _mysql_available():
        pytest.skip("MySQL is not available")
    suffix = uuid4().hex[:8]
    with MySQLStore(f"workforce_test_{tmp_path.name}") as store:
        agent = make_agent().model_copy(update={"id": f"codex_worker_{suffix}"})
        task = make_task().model_copy(update={"task_id": f"task_{suffix}", "assigned_to": agent.id})
        report = make_report().model_copy(
            update={"report_id": f"report_{suffix}", "from_agent_id": agent.id, "task_id": task.task_id}
        )
        event = Event(
            event_id=f"event_{suffix}",
            event_type="task_completed",
            actor_id=agent.id,
            task_id=task.task_id,
        )

        store.save_agent(agent)
        store.save_task(task)
        store.save_report(report)
        store.save_event(event)

        assert store.get_agent(agent.id) == agent
        assert store.get_task(task.task_id) == task
        assert store.list_reports_by_task(task.task_id) == [report]
        assert store.latest_event_sequence() >= 1
        assert store.list_events_after(0)[-1].event == event


def test_file_store_saves_task_scoped_artifacts(tmp_path) -> None:
    store = FileStore(tmp_path)

    stdout = store.save_worker_stdout("task_001", "worker output")
    stderr = store.save_worker_stderr("task_001", "worker warnings")
    diff = store.save_git_diff("task_001", "diff --git a/file b/file")
    test_log = store.save_test_log("task_001", "1 passed", filename="pytest.log")

    assert stdout == tmp_path / "artifacts" / "task_001" / "stdout.log"
    assert stdout.read_text() == "worker output"
    assert stderr.read_text() == "worker warnings"
    assert diff.read_text().startswith("diff --git")
    assert test_log.read_text() == "1 passed"


def _mysql_available() -> bool:
    try:
        store = MySQLStore("workforce_probe")
    except Exception:
        return False
    store.close()
    return True
